### ISSUE TITLE
Remote vs. local

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#28]
@constantinpape 

It is kind of confusing, both on the data storage and also java code level that there are those two folders `local` and `remote` to point to the different locations of the image data. If we have to keep multiple locations maybe we can make it more generic? In principle that could be various local and remote locations? 

I guess by putting everything into S3 we are partly getting rid of this logic anyway?

**Comment by constantinpape** [comment]
These folders are arbitrary already.
In the`images.json`, we store the location of the xmls like this:
```yaml
some_source: {
  "storage": {
    "local": "some/path/to/some_source.xml",  # xml with the local metadata for bdv
    "remote": "some_other/path/to/some_source.xml"  #  xml with the remote metadata for bdv
    }                                        
}
```

By convention we often have `"images/local/..."` and `"images/remote/..."` there, but this is not enforced.
The path only needs to be a valid file w.r.t. the dataset root directory.
